# Carregar dados

In [1]:
ANO = 2015

In [2]:
import pandas as pd

# # Mostrar mais colunas
pd.set_option("display.max_columns", 100)
pd.set_option('display.max_colwidth', 100)

# pandas read txt and decode utf-8 and read until 1000 rows

IDS_PROFISSIONAIS_TI = ["212205", "212210", "212215", "212305", "212310", "212315", "212320", "212405", "212410", "212415", "212420", "317105", "317110", "317115", "317120", "317205", "317210"]

def load_csv(path):
    dtype = {
      'CBO Ocupação 2002': 'string',
      'Motivo Desligamento': int
    }
    
    df = pd.read_csv(
        path, 
        encoding = "ISO-8859-1", 
        sep = ";", 
        decimal = ",", 
        dtype = dtype
        )

    qnt_total = len(df)

    df = df[df['CBO Ocupação 2002'].isin(IDS_PROFISSIONAIS_TI)] 

    print(f"""
    Path: {path}
    Quantidade docs: {qnt_total}
    Quantidade docs filtrados: {len(df)}
    """)

    return df

# df_estados = load_csv(f"./output/bronze/rais_{ANO}/DF{ANO}.txt")

In [3]:
ESTADOS = ["AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO"]

df_estados = [load_csv(f"./output/bronze/rais_{ANO}/{e}{ANO}.txt") for e in ESTADOS]
len(df_estados)

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/AC2015.txt
    Quantidade docs: 191101
    Quantidade docs filtrados: 377

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/AL2015.txt
    Quantidade docs: 694802
    Quantidade docs filtrados: 1817

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/AM2015.txt
    Quantidade docs: 901719
    Quantidade docs filtrados: 3734

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/AP2015.txt
    Quantidade docs: 169873
    Quantidade docs filtrados: 429

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/BA2015.txt
    Quantidade docs: 3338763
    Quantidade docs filtrados: 11049

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/CE2015.txt
    Quantidade docs: 2252709
    Quantidade docs filtrados: 12560

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/DF2015.txt
    Quantidade docs: 1756665
    Quantidade docs filtrados: 24098

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/ES2015.txt
    Quantidade docs: 1454537
    Quantidade docs filtrados: 7209

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/GO2015.txt
    Quantidade docs: 2365769
    Quantidade docs filtrados: 9414

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/MA2015.txt
    Quantidade docs: 998534
    Quantidade docs filtrados: 2216

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/MG2015.txt
    Quantidade docs: 7538791
    Quantidade docs filtrados: 44609

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/MS2015.txt
    Quantidade docs: 1051596
    Quantidade docs filtrados: 3423

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/MT2015.txt
    Quantidade docs: 1396329
    Quantidade docs filtrados: 4161

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/PA2015.txt
    Quantidade docs: 1631230
    Quantidade docs filtrados: 4107

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/PB2015.txt
    Quantidade docs: 887249
    Quantidade docs filtrados: 2905

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/PE2015.txt
    Quantidade docs: 2409994
    Quantidade docs filtrados: 12837


    Path: ./output/bronze/rais_2015/PI2015.txt
    Quantidade docs: 618060
    Quantidade docs filtrados: 2389

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/PR2015.txt
    Quantidade docs: 4756402
    Quantidade docs filtrados: 28739

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (2,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/RJ2015.txt
    Quantidade docs: 6581608
    Quantidade docs filtrados: 50151

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/RN2015.txt
    Quantidade docs: 853661
    Quantidade docs filtrados: 2906

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/RO2015.txt
    Quantidade docs: 539017
    Quantidade docs filtrados: 1071

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/RR2015.txt
    Quantidade docs: 135546
    Quantidade docs filtrados: 429

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/RS2015.txt
    Quantidade docs: 4538011
    Quantidade docs filtrados: 35307

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/SC2015.txt
    Quantidade docs: 3545156
    Quantidade docs filtrados: 16439

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/SE2015.txt
    Quantidade docs: 554872
    Quantidade docs filtrados: 1549

C:\Users\marce\AppData\Local\Temp\ipykernel_16724\2889353533.py:17: DtypeWarning: Columns (7,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

    Path: ./output/bronze/rais_2015/SP2015.txt
    Quantidade docs: 20604435
    Quantidade docs filtrados: 206595


    Path: ./output/bronze/rais_2015/TO2015.txt
    Quantidade docs: 408673
    Quantidade docs filtrados: 1484

27

# Juntando

In [4]:
df_tudo = pd.concat(df_estados)
df_tudo

,Bairros SP,Bairros Fortaleza,Bairros RJ,Causa Afastamento 1,Causa Afastamento 2,Causa Afastamento 3,Motivo Desligamento,CBO Ocupação 2002,CNAE 2.0 Classe,CNAE 95 Classe,Distritos SP,Vínculo Ativo 31/12,Faixa Etária,Faixa Hora Contrat,Faixa Remun Dezem (SM),Faixa Remun Média (SM),Faixa Tempo Emprego,Escolaridade após 2005,Qtd Hora Contr,Idade,Ind CEI Vinculado,Ind Simples,Mês Admissão,Mês Desligamento,Mun Trab,Município,Nacionalidade,Natureza Jurídica,Ind Portador Defic,Qtd Dias Afastamento,Raça Cor,Regiões Adm DF,Vl Remun Dezembro Nom,Vl Remun Dezembro (SM),Vl Remun Média Nom,Vl Remun Média (SM),CNAE 2.0 Subclasse,Sexo Trabalhador,Tamanho Estabelecimento,Tempo Emprego,Tipo Admissão,Tipo Estab,Tipo Estab.1,Tipo Defic,Tipo Vínculo,IBGE Subsetor,Vl Rem Janeiro CC,Vl Rem Fevereiro CC,Vl Rem Março CC,Vl Rem Abril CC,Vl Rem Maio CC,Vl Rem Junho CC,Vl Rem Julho CC,Vl Rem Agosto CC,Vl Rem Setembro CC,Vl Rem Outubro CC,Vl Rem Novembro CC
2422,{ñ c,{ñ c,{ñ c,99,99,99,11,317205,74200,74918,{ñ class},0,4,6,0,2,4,3,44,25,0,1,0,2,120040,120040,10,2135,0,0,2,0,0.00,0.00,851.02,1.07,7420001,1,2,13.2,0,1,CNPJ,0,10,21,851.04,851.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6152,{ñ c,{ñ c,{ñ c,99,99,99,11,317205,53202,64122,{ñ class},0,3,6,0,2,4,5,44,21,0,1,0,9,120020,120020,10,2135,0,0,9,0,0.00,0.00,882.55,1.11,5320202,1,3,19.2,0,1,CNPJ,0,10,20,851.04,1115.81,869.95,851.04,851.04,851.04,851.04,851.04,851.03,0.00,0.00
8869,{ñ c,{ñ c,{ñ c,99,99,99,12,212410,41204,45217,{ñ class},0,2,3,0,0,3,6,20,15,0,0,2,12,120040,120040,10,2062,0,0,9,0,394.00,0.50,390.74,0.49,4120400,1,4,10.0,2,1,CNPJ,0,55,15,0.00,358.18,394.00,394.00,394.00,394.00,394.00,394.00,394.00,394.00,394.00
12426,{ñ c,{ñ c,{ñ c,99,99,99,11,212420,63992,74993,{ñ class},0,5,6,0,4,4,7,44,39,0,0,0,12,120040,120040,10,2054,0,0,9,0,8299.72,10.53,1640.39,2.07,6399200,1,5,15.5,0,1,CNPJ,0,10,19,1000.00,1000.00,1105.00,1035.00,1035.00,1035.00,1035.00,1035.00,1035.00,1035.00,1035.00
14258,{ñ c,{ñ c,{ñ c,99,99,99,12,317110,47512,52450,{ñ class},0,4,6,0,2,1,7,44,25,0,1,3,5,120040,120040,49,2135,0,0,9,0,0.00,0.00,901.99,1.14,4751201,1,3,2.9,2,1,CNPJ,0,10,16,0.00,0.00,1107.54,1245.20,353.23,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404461,{ñ c,{ñ c,{ñ c,99,99,99,0,212405,84116,75116,{ñ class},1,5,5,10,8,8,9,40,33,0,0,0,0,172100,172100,10,1023,0,0,99,0,8036.05,10.19,6699.64,8.49,8411600,2,10,123.4,0,1,CNPJ,0,30,24,5520.93,5520.93,5520.93,5534.26,6151.17,6151.17,6151.17,6151.17,7392.27,10229.59,8036.05
404464,{ñ c,{ñ c,{ñ c,99,99,99,0,212405,84116,75116,{ñ class},1,4,5,7,6,5,9,40,29,0,0,0,0,172100,172100,10,1023,0,0,99,0,3775.75,4.79,3488.31,4.42,8411600,2,10,32.8,0,1,CNPJ,0,30,24,3069.71,3069.71,3069.71,3084.71,3647.73,3647.73,3647.73,3647.73,3647.73,3775.75,3775.75
405921,{ñ c,{ñ c,{ñ c,99,99,99,0,212405,84116,75116,{ñ class},1,6,5,12,10,8,9,40,46,0,0,0,0,172100,172100,10,1023,0,0,99,0,17687.53,22.44,12340.43,15.65,8411600,2,10,253.6,0,1,CNPJ,0,30,24,10254.81,10254.81,12499.97,12574.81,10682.48,10682.48,11817.96,12282.48,12816.61,13265.65,13265.65
406851,{ñ c,{ñ c,{ñ c,99,99,99,0,212405,84116,75116,{ñ class},1,6,5,10,9,8,9,40,43,0,0,0,0,172100,172100,10,1023,0,0,99,0,11247.16,14.27,10441.70,13.24,8411600,2,10,188.5,0,1,CNPJ,0,30,24,9886.93,9886.93,9886.93,9886.93,10299.26,10299.26,10299.26,10299.26,10814.22,11247.16,11247.16
408240,{ñ c,{ñ c,{ñ c,99,99,99,0,212405,85317,80314,{ñ class},1,5,5,9,8,7,10,40,33,0,0,0,0,172100,172100,10,1139,0,0,99,0,5961.89,7.56,6067.38,7.69,8531700,2,10,107.9,0,1,CNPJ,0,30,23,7026.49,6163.19,5961.89,5961.89,5961.89,5961.89,5961.89,5961.89,5961.89,5961.89,5961.89

In [5]:
# df_tudo['Motivo Desligamento', 'CBO Ocupação 2002'].info()

In [6]:
df_tudo["ano"] = ANO
df_tudo.head(2)

,Bairros SP,Bairros Fortaleza,Bairros RJ,Causa Afastamento 1,Causa Afastamento 2,Causa Afastamento 3,Motivo Desligamento,CBO Ocupação 2002,CNAE 2.0 Classe,CNAE 95 Classe,Distritos SP,Vínculo Ativo 31/12,Faixa Etária,Faixa Hora Contrat,Faixa Remun Dezem (SM),Faixa Remun Média (SM),Faixa Tempo Emprego,Escolaridade após 2005,Qtd Hora Contr,Idade,Ind CEI Vinculado,Ind Simples,Mês Admissão,Mês Desligamento,Mun Trab,Município,Nacionalidade,Natureza Jurídica,Ind Portador Defic,Qtd Dias Afastamento,Raça Cor,Regiões Adm DF,Vl Remun Dezembro Nom,Vl Remun Dezembro (SM),Vl Remun Média Nom,Vl Remun Média (SM),CNAE 2.0 Subclasse,Sexo Trabalhador,Tamanho Estabelecimento,Tempo Emprego,Tipo Admissão,Tipo Estab,Tipo Estab.1,Tipo Defic,Tipo Vínculo,IBGE Subsetor,Vl Rem Janeiro CC,Vl Rem Fevereiro CC,Vl Rem Março CC,Vl Rem Abril CC,Vl Rem Maio CC,Vl Rem Junho CC,Vl Rem Julho CC,Vl Rem Agosto CC,Vl Rem Setembro CC,Vl Rem Outubro CC,Vl Rem Novembro CC,ano
2422,{ñ c,{ñ c,{ñ c,99,99,99,11,317205,74200,74918,{ñ class},0,4,6,0,2,4,3,44,25,0,1,0,2,120040,120040,10,2135,0,0,2,0,0.0,0.0,851.02,1.07,7420001,1,2,13.2,0,1,CNPJ,0,10,21,851.04,851.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,2015
6152,{ñ c,{ñ c,{ñ c,99,99,99,11,317205,53202,64122,{ñ class},0,3,6,0,2,4,5,44,21,0,1,0,9,120020,120020,10,2135,0,0,9,0,0.0,0.0,882.55,1.11,5320202,1,3,19.2,0,1,CNPJ,0,10,20,851.04,1115.81,869.95,851.04,851.04,851.04,851.04,851.04,851.03,0.0,0.0,2015

In [9]:
df_tudo["Bairros RJ"].value_counts()

{ñ c    442802
0370     21562
9999      9007
0140      4058
0190      3564
         ...
0530         1
1110         1
1480         1
1270         1
1690         1
Name: Bairros RJ, Length: 143, dtype: int64

# Salvando arquivo

In [15]:
df_tudo["Mês Desligamento"] = df_tudo["Mês Desligamento"].replace("{ñ", -1)
df_tudo["Mês Desligamento"] = df_tudo["Mês Desligamento"].astype(int)

df_tudo["Bairros RJ"] = df_tudo["Bairros RJ"].replace("{ñ c", -1)
df_tudo["Bairros RJ"] = df_tudo["Bairros RJ"].astype(int)

df_tudo["Distritos SP"] = df_tudo["Distritos SP"].replace('           {ñ class}', -1)
df_tudo["Distritos SP"] = df_tudo["Distritos SP"].astype(int)

In [16]:
df_tudo.to_parquet(f"./output/silver/rais_{ANO}_prof_TI_RAIS_VINC_PUB.parquet.gzip", index=False, compression="gzip")